### ISSUE TITLE
v2.0.7 - Thunderbird v91 compatibility - Release Status

### ISSUE THREAD

**Issue by cleidigh** [cleidigh/printing-tools-ng#81]
Beta:
v2.0.7-b1 - first version compatibility - nonfunctional
v2.0.7-b2 - fix options dialog, printer list - nonfunctional
v2.0.7-b3 - partially functional , but toggle orientation to force refresh
v2.0.7-b4 - test - not for community
v2.0.7-b5 - baseline w new printing engine
v2.0.7-b6 - fix atts w web ext, fix hdr name/folder
v2.0.7-b7 - fix selection, print menu,silent printing 
v2.0.7-b8 - add mess win print, rem att list
v2.0.7-b9 - add msg ctx print, add rmv att list opt
v2.0.7-b10 - add win ctx and app menus, fix opts
v2.0.7-b11 - add toolbar, broken
v2.0.7-b12 - fix regression, add observer, menu keys, silent printing 

[x] - first compatibility pass
[x] - investigate new printing engine
[x] - determine dialoguetab listener - thanks to JB
[ ] - Merge observer
[x] - new pview eng interface

@KC-T 
@RRoenn
@kiki-ja
@tidebre67 
@madvinegar

It is going slowly ,however, I am making progress

Christopher

**Comment by tidebre67** [comment]
Christopher, good to seen that you are working on that. 
Slowly is better than nothing. 
First, take care of yourself.

Thomas

**Comment by tbruyere-saluc** [comment]
Hello,
We are currently using this extension in our business. We are very satisfied with the possibilities of the extension. I am in the process of planning the migration to thunderbird 91.x in our company.
How can I help update your extension to thunderbird 91.x?
I can participate in the test, I can finance development, I can translate ...

**Comment by 3LaHoonK** [comment]
Hi,

A plug-in update is required to be compatible with the latest version of thunderbird

An automatic printing problem is required


Waiting for an update, thank you

**Comment by DeniCko** [comment]
Hi, really looking forward to updating this great add-on.

**Comment by reinerblock** [comment]
Is there any schedule for the release because I really missing it.

**Comment by KC-T** [comment]
Truly understand that this is voluntary work.

I have been saying no to the prompt to update to version 91 issued by Thunderbird on a daily basis.

**Comment by vtrasikis** [comment]
Hi,  I also am missing this great product.. I am also willing to help in testing the new release.

**Comment by Francewhoa** [comment]
Hello @Alpengreis, @pechh, @tbruyere-saluc, @vtrasikis and all enthusiasts of PrintingTools :) 

I'm a user and volunteer like you. You expressed that you were interested to contribute testing of the beta version of PrintingTools for Thunderbird 91.x. If you're not familiar with how to text a beta add-on. Find the suggested steps below. Those steps are for users. You do not need developer skills. All you need is Thunderbird & an internet browser. To click your way though those steps below.

## Steps
1. Using Thunderbird, if you already have installed PrintingTools NG add-on, you need to remove it. 
    * Note: Why removing it? Because in the steps below, we'll install PrintingTools NG beta version for testing. Thunderbird does not allow the same add-on to be installed twice.
2. Using any internet browser to your liking, for example, [Firefox](https://mozilla.org/firefox), go to this PrintingTools NG beta version 2.0.7 branch page at https://github.com/cleidigh/printing-tools-ng/tree/v2.0.7/xpi 
to download the appropriate most recent beta version of the `.xpi` file. 
   * Notes
       * For example, as of January 2nd, 2022, the most recent version of PrintingTools NG beta version is this xpi file [printing-tools-ng-2.0.7-b3-tb.xpi](https://github.com/cleidigh/printing-tools-ng/raw/v2.0.7/xpi/printing-tools-ng-2.0.7-b3-tb.xpi)
        * One frequent challenge is that when you install the .xpi file, Thunderbird displays an error message saying that this file is corrupted. To resolve this challenge, in the other action above, when you download the xpi file, double-check that you left-click on the appropriate "download" button. Instead of right click and download from the branch folder.
4. Using Thunderbird, manually install this `.xpi` file. If you're not familiar with this, find this [documentation page](https://support.mozilla.org/en-US/kb/installing-addon-thunderbird#w_a-slightly-less-ideal-case-install-from-a-downloaded-xpi-file).
5. Test this beta version. During your testing, when you find a challenge (bug), or if you have a suggestion, below are the suggested steps :
   1. Create one ticket per challenge at https://github.com/cleidigh/printing-tools-ng/issues/new
   2. In your Ticket above, to speed up & facilitate communications, it is suggested to include:
        1. Steps to reproduce the challenge. Using a numbered list format.
        2. Which beta version of PrintingTools NG
        3. Which browser & its version
        4. Which operating system & its version 
6. Done. You have successfully tested a beta version of PrintingTools NG and created a Ticket(s). Thanks for your contribution :)

**Comment by KC-T** [comment]
An issue ticket has been submitted.

**Comment by Francewhoa** [comment]
@KC-T is referring to his issue/ticket #89

Thanks for your testing contribution @KC-T :)

**Comment by cleidigh** [comment]
All
I am back!
update
i have been transitioning to eye gaze programing so very slow
good news is i have a test working in91 that uses new preview adds borders and colors 
now i have to integrate
this might take a bit but i wanted to let all know
@cleidigh

**Comment by Francewhoa** [comment]
> i have been transitioning to eye gaze programing 

Welcome back @cleidigh, :) Thanks for courageously transitioning to eye gaze programming (EGP). I'm guessing this is to adapt to your mobility challenge.

I'm not familiar with EGP. So to educate myself, I found this short introduction video at https://youtu.be/J4cj6r2QrHM Seems like an amazing technology. Is this type of technology what you meant by EGP?

>so very slow

Take as much time as you need. One of many benefits with contributing to a Libre/Open Source product, such as like PrintingTools NG, is that you can set both your own pace and workload.

I look forward to your future contributions

**Comment by KC-T** [comment]
Modern version of what Stephen Hawking used?

**Comment by tidebre67** [comment]
Christopher,
i am glad to learn that you are WELL and back.
Comgratulation that you managed to get the Eye gaze technology.
As far as printingtools-ng is concerned, dont hurry.
I am still on v78 on my desktop pc as the print preview window for me is by far to small and there is no zoom function on v91.
On notebook on v91 for further testing.

**Comment by cleidigh** [comment]
@Francewhoa 
it is my ext so i want to support it as long as i can!

@Francewhoa 
@KC-T 
yes i am using tobii since i have als like SH (just not as smart ;-) )
https://www.tobii.com/

**Comment by cleidigh** [comment]
All

I have resumed updt top of thread
b4 is not std - ignore
b5 is "new pv baseline"
- basic tests
-  borders, colors, cc, bcc look ok
-  att table not wrk need new method
-  no ab yet
-  use temp "PTNG Print"
-  please help test to find other issues this will help me alot!

@cleidigh

**Comment by 3LaHoonK** [comment]
Hello ,

@cleidigh 

Cannot print automatically

When pressing PTNG Print, only the last message received works

Awaiting your reply, thanks

**Comment by cleidigh** [comment]
@3LaHoonK 
right now you can only print the selected msg in the list 

can you describe what automatic means?
@cleidigh

**Comment by 3LaHoonK** [comment]
Hello,,
@cleidigh 

I mean any mail that receives an automatic mail print

Video explaining how to automatically print mail or invoice

2.0.7 version is not working

https://www.youtube.com/watch?v=8qIafd4xLgg&ab_channel=GeorgiBakalski


Awaiting your reply, thanks

**Comment by tidebre67** [comment]
as far as i can see  works version 2.07-b6 for my purposes perfect via PTNG print . tks a lot.

**Comment by kiki-ja** [comment]
All.

About "**PTNG Print**".

Christopher hasn't explained it yet, but I'm assuming "**PTNG Print**" means printing with Printing Tools NG and "**Print**" means printing with Thunderbird.

@3LaHoonK
I guess auto-printing doesn't work because I can't print with "PTNG Print" at the moment.
If you use Thunderbird "Print", you can print automatically, right?

**Comment by 3LaHoonK** [comment]
Hello
@kiki-ja

How Thunderbird Automatic Print?

**Comment by kiki-ja** [comment]
@3LaHoonK 

Printing Tools NG **2.0.7-beta does not work properly yet.**
Because it is **still under development and not yet finished**.
It is currently in **the beta testing stage**.
"**PTNG Print**" will **only work manually**.

Normal automatic printing using the "FiltaQuilla" add-on will work.

**Comment by 3LaHoonK** [comment]
Hello

@kiki-ja 

I'm on the same video 

Use the add-on of both at the same time


FiltaQuilla + Printing Tools NG

https://www.youtube.com/watch?v=8qIafd4xLgg&ab_channel=GeorgiBakalski

Is there only a way to work FiltaQuilla?

**Comment by madvinegar** [comment]
Is "print selection" working for you? that is to highlight with the cursor a specific part of the email and print just that.
(Ofcourse "print selection when it exists" box is ticked in printing options).

**Comment by kiki-ja** [comment]
@3laHoonk

I've already seen the YouTube video.
The only way to enable auto-printing in Thunderbird would be to use FiltaQuilla.
**The reason for this is that Thunderbird does not have a "Print" action in its message filters.**

Examples of possible combinations:
Thunderbird 78.0 series + FiltaQuilla 3.3
or
Thunderbird 78.0 series + FiltaQuilla 3.3 + Printing Tools NG 2.0.61
or
Thunderbird 91.0 series + FiltaQuilla 3.3

**Please note that this is not a support site for add-ons for automatic printing.
This is not a support site for autoprinting add-ons, but a place to discuss Printing Tools NG Beta topics.**

**Comment by kiki-ja** [comment]
@madvinegar 

See below, which has already been commented on.

"2.0.7 Beta Test Reports"
https://github.com/cleidigh/printing-tools-ng/issues/80#issuecomment-1025477996
https://github.com/cleidigh/printing-tools-ng/issues/80#issuecomment-1025585818
https://github.com/cleidigh/printing-tools-ng/issues/80#issuecomment-1025677277

**Comment by cleidigh** [comment]
all:
@kiki-ja is exactly  right PTNG print is temporarily  being  used to do experiments 
until i figure out  menu wireing
will  post  more tomorrow 
@cleidigh

**Comment by cleidigh** [comment]
quick  straw poll:

what  do people think  about  depreciation of  address  book functionality ?

this  could  save  a lot  of development 
@cleidigh

**Comment by tidebre67** [comment]
never used the address book functionality, therefore no benefit for me.

**Comment by kiki-ja** [comment]
@cleidigh

>what do people think about depreciation of address book functionality ?

I know that some users use the print function of the address book.
I think it would be a good idea to have a separate Issues section to solicit feedback.

On the other hand, if Christopher Leidigh thinks that developing an address book printing feature would be a burden, I have the following suggestion.

**[Priority 1]** Complete (release) version 2.0.7 without the address book printing feature first.
**[Priority 2]** Add the address book printing function if requested later.

I hope this is helpful.
I'm sorry.

**Comment by tidebre67** [comment]
> **[Priority 1]** Complete (release) version 2.0.7 without the address book printing feature first. 
**[Priority 2]** Add the address book printing function if requested later.

***
good idea. support this suggestion

**Comment by madvinegar** [comment]
> @cleidigh
> **[Priority 1]** Complete (release) version 2.0.7 without the address book printing feature first. **[Priority 2]** Add the address book printing function if requested later.

I support this suggestion too.

So, to summarise, print selection works with 2.0.7-b7 but you need to open the email in a tab (and not in a separate window).
Is it worth fixing this to also work when you open the email in a new window?

**Comment by RRoenn** [comment]
> All I am back! 
@cleidigh
I am very happy that you are well. Take your time. Best wishes.

**Comment by kiki-ja** [comment]
@cleidigh
All.

I would like to summarize what we have achieved so far in version 2.0.7 beta. --

**１．It is now possible to do the same things as in version 2.0.61.**
　-It is now possible to check in Print Preview.
　-Attachment list can be displayed in the header.
　-Single text selection and printing are now possible.
　-Other.

**２．New issues, requests, and unresolved problems.**
　-Hide the attachment list at the bottom of the message. (New)
　-Selecting multiple texts and printing them. (New)
　-Printing when a message is opened in a window. (This was not possible with version 2.0.61.)

@kiki-ja

**Comment by kiki-ja** [comment]
@RRoenn

>This isn't working also in old thunderbird versions (e.g. 78). But works in 52.9

Yes. It's the same for me.

>I didn't know that you can select different text passages, but it only prints the first selection. Did this work in older versions? (not with my old 52.9)

Single text selection and printing are  possibled on PrintingTools NG 2.0.61.
The supported version of PrintingTools NG 2.0.61 is Thunderbird 68-90.

Please see below.
https://github.com/cleidigh/printing-tools-ng/issues/80

@kiki-ja

**Comment by 3LaHoonK** [comment]
Hello all ,,

@kiki-ja @cleidigh 

The header of the page does not disappear in print

selected red color

Thunderbird 91.5.1
PrintingTools NG Version 2.0.7-b7

We are waiting for you and thank you

![image](https://user-images.githubusercontent.com/30515994/152411228-dc4eeb4d-808d-40cf-9048-b38da66ce800.png)

![image](https://user-images.githubusercontent.com/30515994/152411401-b36ca1ac-630c-4fab-ba8d-d205a546dd4d.png)

![image](https://user-images.githubusercontent.com/30515994/152411477-7e2def6a-48f3-4bb4-bdb6-4a00df6804d1.png)

**Comment by reinerblock** [comment]
Perhaps you chose the wrong icon/menu item?

I'm using beta 7 and am already happy. Because now it's integrated into the normal/default print dialog and the header is as it should be because of my settings; as you can see with the screenshot of a commercial email.

![grafik](https://user-images.githubusercontent.com/5745579/152417771-6b8a7107-14dc-4d75-9551-43a42b8647db.png)

O.k., don't say anything about how strange it is that a vendor for printer supplies sells clinical thermometers. ;)

**Comment by cleidigh** [comment]
@3LaHoonK 
I just tried to reproduce your issue without success 
I used all your settings 
I noticed your headers are not aligned either 
can you try setting the border 
also how are you initiating print? 
@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh

This is my request.
This is a new feature, but pass and through is not a problem.

- I would like to see an icon added to the Thunderbird toolbar.
I would like to see three actions when clicking the icon: [Open PTNG Options Dialog], [Open Print Preview], and [Print].

@kiki-ja

**Comment by kiki-ja** [comment]
@3LaHoonk

>The header of the page does not disappear in print

Please see below.
"2.0.7 Beta Test Reports"
https://github.com/cleidigh/printing-tools-ng/issues/80#issuecomment-1028704718

**Attention!**
When printing with PrintingTools NG 2.0.7-b7, you need to go to the Menu bar > [File] > [Print…]
The same is true for 2.0.7-b8.

@kiki-ja

**Comment by kiki-ja** [comment]
**All.**

**Attention!**
When printing with PrintingTools NG 2.0.7-b8, you need to go to the Menu bar > [File] > [Print…]

@cleidigh is working on integrating it into the context menu of Thunderbird as well.
@cleidigh wrote:
>PTNG print is temporarily being used to do experiments
>until i figure out menu wireing

From:https://github.com/cleidigh/printing-tools-ng/issues/81#issuecomment-1026467955

@kiki-ja

**Comment by madvinegar** [comment]
> Hello all ,,
> 
> @kiki-ja @cleidigh
> 
> The header of the page does not disappear in print
> 
> selected red color in photos
> 
> Thunderbird 91.5.1 PrintingTools NG Version 2.0.7-b7
> 
> We are waiting for you and thank you
> 
> ![image](https://user-images.githubusercontent.com/30515994/152411228-dc4eeb4d-808d-40cf-9048-b38da66ce800.png)
> 
> ![image](https://user-images.githubusercontent.com/30515994/152411401-b36ca1ac-630c-4fab-ba8d-d205a546dd4d.png)
> 
> ![image](https://user-images.githubusercontent.com/30515994/152411477-7e2def6a-48f3-4bb4-bdb6-4a00df6804d1.png)

Are you opening the email in a new window or in a tab?

**Comment by tidebre67** [comment]
all,
as Christopher mentioned earlier PrintingTools-NG 2.07...  are still beta versions and there is still a lot to do before finalised.
Just to remind if testing do not use the 'Print' button but use print via 'file'. See below. A lot is already working here.
![image](https://user-images.githubusercontent.com/44371934/152528200-5c04bedc-1173-4fa9-bf74-06586b2dc4f5.png)

**Comment by reinerblock** [comment]
Why is it necessary to explain such a simple thing multiple times? <facepalm>

**Comment by tidebre67** [comment]
quite simple, because some havent noticed and mention issues which work when using as described.

**Comment by cleidigh** [comment]
All

can people check hide images in b8
i see it working 
@cleidigh

**Comment by 3LaHoonK** [comment]
Hello 

@cleidigh 

Either work with File > Print
It works without problems and the header of the page disappears


---------------

When you print by selecting a right click button from a mouse, the problem of showing the header of the page appears

--------------

For example, automatic printing is done in tools > message filters
There is a problem with the header of the page not being hidden


Waiting for a response and a solution to the problem, thank you

![image](https://user-images.githubusercontent.com/30515994/152635439-28e2b735-c8d6-4b1f-9453-e54317723849.png)

**Comment by tidebre67** [comment]
> All
> 
> can people check hide images in b8 i see it working @cleidigh

confirm, works

@tidebre67

**Comment by kiki-ja** [comment]
@cleidigh
All.

This is a summary of PrintingTools NG 2.0.7 beta.(Up to beta8.)

**Possible and achieved**
- [x] It is now possible to check in Print Preview.(beta3)
- [x] Header borders,color,cc,bcc.(beta5)
- [x] Attachment list displayed in the header.(beta6)
- [x] Single text selection and printing.(beta7)
- [x] Remove attachments list at the bottom of the message.(beta8)
- [x] Printing a message opened in a window.(beta8)
- [x] Hide the images option.(beta8)
　
>２．New issues, requests, and unresolved problems.

**Add**
- [ ] Add show / hide toggle option. (Remove attachments list at the bottom of the message.) #80
- [ ] Integrate to all Thunderbird "Print" menu. #80 #81
- [ ] Hide inline attachments option not worked. #80
- [ ] Print eml files and attachmments to messages #5
- [ ] Print encrypted e-mails #7
- [ ] Print group (or category) of contacts #16
- [ ] Add "Reply-To" to header #87

Note:
If there are any mistakes, omissions, missing please point them out.

@kiki-ja

**Comment by tidebre67** [comment]
@kiki-ja 
as far as i can see there is no attachment list at the end of the message any more. pls check once again.

**Comment by kiki-ja** [comment]
@tidebre67 

> as far as i can see there is no attachment list at the end of the message any more.

Yes, me too.
Please see below.

> **Possible and achieved**
> - [x] Remove attachments list at the bottom of the message.(beta8)

Should I change "Possible and achieved" to another term?
For example, Fixed? or Complete?

**Apology:**
I am Japanese, and I am not good at languages other than Japanese.
If there is something wrong with my English, please let me know.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
No apologies for your English, it is excellent compared to my 20 words of Japanese from my trips to Japan many years ago  ;-)!
your guidance and help tracking progress is invaluable and so helpful !!
Thanks 

I suggest we do the following : 

- agree on current status with defined categories : 
- categories : 
Formating and functionality  (2.0.6 baseline)
Invocation paths and methods (notes to follow)
New potential features - rank and decide what to attempt for release 

Then i suggest starting a new issue  to be clean 

what do you think?
@cleidigh

**Comment by cleidigh** [comment]
Important Note on PTNG Operation for TB 91:

the print architecture has changed significantly, in78- PTNG used the interception method of detecting the print page DOM load,then manipulating the headers etc.,then completing the print.
For  91+ this method is not possible.  Additionally, new security policy prevents many old approaches.  There have also been several changes to the actual mail output format which is why I could not initially reproduce the attachment list issue.

So i need people to understand 2 things, first is that the basic Formating issues are generally not problematic as long as I have all the information.  I had to get the attachment information and create a new table.

Invocation is the big problem, since I cannot intercept, it means 2 things, first we must find all invocations of the print operation and find methods to override them with pTNG. Second issue is that other print clients such as FiltaQuila that I suspect invoke the print command directly will not invoke PTNG.

I will check with Axle on this tomorrow.  I am already looking at the other Invocation  methods to solve this issue.  

in the meantime I have gotten the right click context menus and the " hamburger" app menu working with some outstanding problems.

Please let me know if this is clear and any thoughts, sorry for the details , but this is important.

@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh 

>your guidance and help tracking progress is invaluable and so helpful !!

Thank you very much.

>I suggest we do the following : 

I support the consensus.

>New potential features - rank and decide what to attempt for release 

There are some things you can do and some things you can't, so i think it's better to let them decide.

>Then i suggest starting a new issue  to be clean 

I support the consensus.
If possible, it would be good to sort past issues into labels such as bug, pend, feature, enhancment, duplicate, invalid, wontfix, layout, etc., as well as open and closed issues.
It is good to close #80 for the sake of cleaning.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
after some feedback on b9 can you help with making that list?
@cleidigh

**Comment by cleidigh** [comment]
Invocation methods in b9:

- File\Print main menu 
- Message context menu (right click over msg item in list)
- Message context menu (right click over msg in bottom pane)
- - Message context menu (right click over msg in tab
- File\print menu in tab
- File \print in separate message window 
- App menu print ( hamburger menu)

need to determine if this is complete 

@cleidigh

**Comment by KC-T** [comment]
Just tested 2.0.7-b9-tb on Windows 11.
Changed date format cannot be saved.
Hide inline attachment list can be selected and saved, and works,
Border around headers not stable. Did not appear after installing the add-on.  Did appear after re-starting Thunderbird. Disappeared again when testing an email. Appeared again when further testing other emails.
Align the headers can be selected and can work but not saved for the next time.
Changed style settings cannot be saved.
No selection for fonts.
Only a word "Headers" appears in the Headers order menu. Cannot be changed. Though the printed order is my previously set order, possibly left over from previous setting.
Default printer cannot be selected.
Thunderbird's page setup menu option disappeared. Overridden? Should be kept.

K C

**Comment by kiki-ja** [comment]
@cleidigh 

>after some feedback on b9 can you help with making that list?

I will be happy to assist you if I can.
I would like to send you a separate email at test1@kokkini.net, is that okay?

@kiki-ja

**Comment by kiki-ja** [comment]
@KC-T 
@cleidigh 

https://github.com/cleidigh/printing-tools-ng/issues/81#issuecomment-1031121704
It's the same for me.

@kiki-ja

**Comment by tidebre67** [comment]
confirm KC-T comments.

**Comment by RRoenn** [comment]
Tb v91.5.1 german
v2.0.7-b9 (restarted after update)

@all I'm sorry, I don't have that much time at the moment for testing

I can't save ''Attachments per Line''
I can't save ''Align the headers''

Order of Header menu is missing
Can't select default printer


![options](https://user-images.githubusercontent.com/77779094/152820429-3ca2c5f0-4bf1-4d12-a424-4d5eed9132f2.PNG)
![orderHeader](https://user-images.githubusercontent.com/77779094/152820434-bb3af45a-7914-48c9-9b38-99333659df6b.PNG)
![defaultPrinter](https://user-images.githubusercontent.com/77779094/152820435-68ac88e0-f497-4274-9451-f27adc67d7e0.PNG)

**Comment by cleidigh** [comment]
All
The configuration issues were an error on my part after removing the config button  option 
I confirmed the lack of saving the various items mentioned

@KC-T your observation about the borders is the only issue I could not reproduce, let's track this in b10 after fixing the config save

**Comment by cleidigh** [comment]
All

b10 notes

- fixed  b9 option saving problem 
- added ctx and app menus to separate windows 
- fixed edge conditions for no selected msg
- "Print... (NG)" used for menus - maybe temporary 
note!

if you see a menu that only shows "Print..." it is NOT overriden  - please report 

It may be good to have the NG in the final release, thoughts ?

@cleidigh

**Comment by kiki-ja** [comment]
@cleidigh 
ALL

> b10 notes
> 
>     * fixed  b9 option saving problem
> 
>     * added ctx and app menus to separate windows
> 
>     * fixed edge conditions for no selected msg
> 
>     * "Print... (NG)" used for menus - maybe temporary

I was able to check. Good!
 
> if you see a menu that only shows "Print..." it is NOT overriden - please report

All of them were "Print...(NG)".
 
> It may be good to have the NG in the final release, thoughts ?

It would be better if the version 2.0.61 base is prioritized.

@kiki-ja

**Comment by reinerblock** [comment]
I got a difference between printing by clicking on the icon above the message header and the menu item "File"->"Print... (NG)".

![grafik](https://user-images.githubusercontent.com/5745579/153208919-8be43bf5-082f-49d0-a620-402e5b1b8c08.png)

The result is the following.

![grafik](https://user-images.githubusercontent.com/5745579/153208992-28aeafcd-9d21-4c50-b0bb-61995b5e92c2.png)

The result by printing by using the menu item.

![grafik](https://user-images.githubusercontent.com/5745579/153209079-84024727-1f0b-47bb-bb4e-faf150d219e8.png)

As you can see, in the latter one the text of the email is completely on the second page whereas the default print dialog puts the text on mostly (at least starts) on the first page.

**Comment by KC-T** [comment]
Note also the absence of border around the headers in the first image.

**Comment by reinerblock** [comment]
The second screenshot is the default TB print dialog without the PrintingTools NG settings. Therefore the background of the header in the third screenshot has a different color. I took two other screenshots of  emails with an attachment. There you can see that the attachment is just visible in the second screenshot (of PT NG),

![grafik](https://user-images.githubusercontent.com/5745579/153213451-792bda73-46f6-43dd-b4d9-9c7096a34d5e.png)

![grafik](https://user-images.githubusercontent.com/5745579/153213733-cec9c263-05bf-477b-beac-6e0aec7be52b.png)

Another difference is that there's no graphic inside, and the text starts on the first page.

**Comment by KC-T** [comment]
My feedback after testing 2.0.7-b9-tb on Windows 11 {Further feedback based on b10.]
Changed date format cannot be saved. {Resolved.}
Hide inline attachment list can be selected and saved, and works, {Same.]
Border around headers not stable. Did not appear after installing the add-on. Did appear after re-starting Thunderbird. Disappeared again when testing an email. Appeared again when further testing other emails. {Resolved. Boder appears when using Print (NG). **But, Print NG not activated if using Ctrl-P**.]
Align the headers can be selected and can work but not saved for the next time. [Resolved.]
Changed style settings cannot be saved. [Resolved.]
No selection for fonts. [Resolved.]
Only a word "Headers" appears in the Headers order menu. Cannot be changed. Though the printed order is my previously set order, possibly left over from previous setting. [Resolved.]
Default printer cannot be selected. [Resolved.]
Thunderbird's page setup menu option disappeared. Overridden? Should be kept. [Still not available even after removing Print NG.]

**Comment by cleidigh** [comment]
@reinerblock 
good catch on the icon
this is the problem with the override method you have to find all Invocation methods !

I am going to take  @kiki-ja suggestion and do a ptng print icon with print, preview  and options 

can you send me the problematic emails so I can reproduce?
use : 
test1@kokkini.net

@cleidigh

**Comment by cleidigh** [comment]
@KC-T 
I will will see about getting ctrl-P working 
also note i still have to get Uninstall working 
restart after for aclean setup 
b11 will have this resolved 
@cleidigh

**Comment by tidebre67** [comment]
@cleidigh 
very good progress, tks a lot.
tested b11:
new toolbar button Print NG  works perfect, except in open message in a new window, there no reaction.
Print...(NG) (D) under File not working anymore.
as far as i can see control P is not working.

**Comment by kiki-ja** [comment]
@cleidigh 
All

This is a summary of PrintingTools NG 2.0.7 beta. Up to beta11.

**Possible, fixed, resolved, and achieved**
- [x] It is now possible to check in Print Preview.(beta3)
- [x] Header borders,color,cc,bcc.(beta5)
- [x] Attachments list displayed in the header.(beta6)
- [x] Single text selection print.(beta7)
- [x] Remove attachments list at the bottom of the message.(beta8)
- [x] Printing a message open in a window.(beta8)
- [x] Hide the images option.(beta8)
- [x] Add show/hide toggle option (Remove attachments list at the bottom of the message).(beta10) #80
- [x] Integrate to all Thunderbird "Print" menu.(beta10) #80 #81
- [x] Hide inline attachments option not worked.(beta10) #80
- [x] Add new PTNG toolbar button.(beta11) #93
- [x] Fixed clean uninstall.(beta11) #81

**New issues, requests, and unresolved problems**
- [ ] Regression App menu, Context menu, Print... (NG), Ctrl+P operation #80 #81
- [ ] Selecting multiple texts and printing them #80
- [ ] Print eml files and attachmments to messages #5
- [ ] Print encrypted e-mails #7
- [ ] Print group (or category) of contacts #16
- [ ] Add "Reply-To" to header #87
- [ ] Integrate to "Print" icon of header view toolbar #81
- [ ] Font size and image layout are different in HTML message printing #80
- [ ] Integrate PTNG with FiltaQuila add-on for automatic printing #94

Note:
If there are any mistakes, omissions, and missing, please point them out.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
thanks for doing the list 

I was hoping to post b12 , however, I am not there yet 

some comments on the list 

what is "Integrate into print icon..."?

we should add @reinerblock issue not seeing button in tb pallet 

for additions
reply -to - not now, to difficult 
encrypted email - same
no contact stuff now

others I will address 

hopefully b12 tomorrow with most done 
@cleidigh

**Comment by reinerblock** [comment]
It's all o.k. now regarding the icon. I uninstalled the beta and reinstalled it again, and then I found the icon and could place it on the toolbar. And it's working as it should. Just would be nice if there were an icon for the mail header toolbar, too.

**Comment by kiki-ja** [comment]
@cleidigh 
All

>what is "Integrate into print icon..."?

I'm sorry. I've added it to #93.
>we should add @reinerblock issue not seeing button in tb pallet

I see this issue has been resolved as @reinerblock commented.
>for additions
>reply -to - not now, to difficult
>encrypted email - same
>no contact stuff now

I understand.
I just listed the issues that have been posted so far as a summary.
The reason for this is to organize a lot of issues and make them easier to understand.
Please understand.
Naturally, I believe that @cleidigh should decide whether or not to work on developing these in a new way.

@kiki-ja

**Comment by cleidigh** [comment]
> It's all o.k. now regarding the icon. I uninstalled the beta and reinstalled it again, and then I found the icon and could place it on the toolbar. And it's working as it should. Just would be nice if there were an icon for the mail header toolbar, too.

@reinerblock 
Great to hear that it was a reinstall issue, byproduct of the prior lack of a clean uninstall process 

Track the toolbar issues in #93 
I will also have some behavior questions 
@cleidigh

**Comment by cleidigh** [comment]
@tidebre67 
all

the compose window does not have headers show n
normally  so i cannot either

**Comment by tidebre67** [comment]
@cleidigh 
Christopher sounds logical

**Comment by kiki-ja** [comment]
@cleidigh 
All

2.0.7-b12 test report.
OS: Windows 10 Pro 21H2 64bit
Thunderbird 91.6.1 64bit

App Menu, Context Menu, Print... (NG), Ctrl+P behavior regression has been fixed.

**Comment by librelegal** [comment]
Testet b13 with Linux debian 10: listing of attachments works with new button Print... (NG), but not with crtl-P

**Comment by kiki-ja** [comment]
@cleidigh 
All

I have added my comments below.
https://github.com/cleidigh/printing-tools-ng/issues/80#issuecomment-1046820000

@kiki-ja

**Comment by cleidigh** [comment]
@librelegal 
when you say " attachment list" do you mean the list in the headers?
also what are you printing  and where are you printing  when ctrl-P does not work?
@cleidigh

**Comment by librelegal** [comment]
Hi cleidigh: Thank you a a lot for what allowing us to continue using thunderbird via your optimizations.

Under Linux debian 10 with thunderbird 91.6.0, 46 but crtl-P does not work, actually no priting method or preview works, only the new button Print NG within a message. There I can see the attachments listed in the header box.

**Comment by librelegal** [comment]
Under Windows 10 I observed the same

**Comment by cleidigh** [comment]
@kiki-ja 
All

b14 - feature complete release candidate - loc and cleanup in b15

- added external print with FiltaQuila (req beta fq -see #94 )
- debug options 
- menus localized (not buttons)
- clean debug output 
- tested fairly well 

debug options : 

under global printing options you can set a string with space separated keywords.

initialsource - dumps initial message source before formating
finaloutput - dumps formatted msg
passthrough - skips formatting - should always match tb print

We should be able to use for debugging html/img issues etc.

I will be cleaning up as people test also I will request some opinions on some localization items

Lets open individual issues with b14 in title
we already have several which can be updated for b14 results 

I think we are just a bit away!

@cleidigh 


dgb opts, note i changed first letter of passthrough to negate

![image](https://user-images.githubusercontent.com/25272315/155427909-0e6d50f2-ca73-4bd3-adfb-0b1dc8103c3b.png)

**Comment by 3LaHoonK** [comment]
Hello all,,,

@cleidigh 

thunderbird v 91.6.1
PrintingTools NG v 2.0.7-b14p1

Tools > Message Filters > New...

We need to add a Print (NG) button in perform these actions: Print (NG)

Awaiting your reply, thanks

![image](https://user-images.githubusercontent.com/30515994/155461801-2980dfb1-2b53-4d1c-99cc-701a1707ada7.png)
![image](https://user-images.githubusercontent.com/30515994/155461812-be590b92-0e2b-4dde-bb6b-b2d2cc954347.png)

**Comment by cleidigh** [comment]
@3LaHoonK 
can you track this in #94 
Also clarify more I don't understand what you are suggesting be added to ptng
@cleidigh

**Comment by kiki-ja** [comment]
@3LaHoonk

I have written a question for you below.
"Integrate PTNG with FiltaQuila for automatic printing" https://github.com/cleidigh/printing-tools-ng/issues/94#issuecomment-1050573372
From now on, this issue should be handled there.

@kiki-ja

**Comment by cleidigh** [comment]
@kiki-ja 
All

I posted  b15 with an external q and full localization 
This is feature and UI localization complete.
 
I intend to start a new issue to track.

https://github.com/cleidigh/printing-tools-ng/blob/v2.0.7/xpi/printing-tools-ng-2.0.7-b15-tb.xpi

@cleidigh

**Comment by cleidigh** [comment]
@kiki-ja 
@KC-T 
@jobisoft
@tidebre67 
@reinerblock
@querixg
@RRoenn
@madvinegar
@ditchfinder
@3LaHoonK
@realraven
@librelegal
@Francewhoa

As you hopefully all know v2.1.0 was released, thank you for all the help!

I am working on some issues and adding multiple selection support 
please see #100 & 
#99 

I will be starting to work on the next esr support so we are ready out the gate!
@cleidigh

**Comment by pechh** [comment]
great job guys!!
you were all incredible!!
------------------------------------------------------------------------
*From:* Christopher Leidigh ***@***.***
*Sent:* Monday, March 14, 2022, 01:37
*To:* cleidigh/printing-tools-ng
*Cc:* pechh; Mention
*Subject:* [cleidigh/printing-tools-ng] v2.0.7 - Thunderbird v91 
compatibility - Release Status (#81)

**Comment by madvinegar** [comment]
@cleidigh 
Cristopher you are the one that should get all the credit. Thank you so much for your hard work.

**Comment by cleidigh** [comment]
@pechh 
@madvinegar 
Thank you both for your support, words and help!
@cleidigh

**Comment by Francewhoa** [comment]
> @Francewhoa
> 
> As you hopefully all know v2.1.0 was released, thank you for all the help!

Thanks @cleidigh and all contributors ♥ :) I look forward to trying it

BTW, you can expect a slow response time from me. As I'm presently sick and in a long recovery. It's not Covid and I'm feeling better every day :) I look forward to resuming my contributions when I'm fully recovered :)
